Part 1: Theoretical Questions
1. What are the different data structures used in TensorFlow? Give some examples.
TensorFlow provides several data structures designed to facilitate efficient computation and data manipulation for deep learning tasks. The primary data structures include:

Tensors:

Definition: Tensors are multi-dimensional arrays that can hold various types of data, such as integers, floats, and strings. They are the fundamental building blocks in TensorFlow, enabling efficient mathematical computations.

In [1]:
import tensorflow as tf
tensor_example = tf.constant([[1, 2], [3, 4]])
print(tensor_example)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Constants:

Definition: Constants are immutable tensors whose values cannot be changed once defined. They are useful for representing fixed values in computations.

In [2]:
const_example = tf.constant(3.14)
print(const_example)


tf.Tensor(3.14, shape=(), dtype=float32)


Variables:

Definition: Variables are mutable tensors whose values can be changed during model training. They are primarily used to store parameters (weights and biases) that the model learns.

In [3]:
variable_example = tf.Variable(tf.random.normal([2, 2]), name='weights')
print(variable_example)


<tf.Variable 'weights:0' shape=(2, 2) dtype=float32, numpy=
array([[0.1353603 , 0.08663481],
       [0.33493122, 0.282276  ]], dtype=float32)>


Sparse Tensors:

Definition: Sparse tensors are designed to represent data that is mostly empty (i.e., consists of many zeros). They save memory and improve computation efficiency.

In [6]:
import tensorflow as tf

# Define indices as int64
indices = tf.constant([[0, 0], [1, 2]], dtype=tf.int64)
values = tf.constant([3, 4])  # Default dtype is int32, which is fine
shape = tf.constant([3, 4], dtype=tf.int64)  # Ensure the shape is also int64

# Create the sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices, values, shape)

# Convert sparse tensor to dense format and print
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print(dense_tensor)


tf.Tensor(
[[3 0 0 0]
 [0 0 4 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


Datasets:

Definition: TensorFlow datasets allow for efficient input pipelines for training models, enabling easy manipulation of large datasets, including batching and shuffling.

In [7]:
dataset_example = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
for element in dataset_example:
    print(element.numpy())


1
2
3
4
5


2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
TensorFlow Constant:

Characteristics:

Immutable: Once created, the values cannot be changed.
Use Case: Useful for representing fixed values in computations, such as hyperparameters or constants in mathematical equations.

In [8]:
import tensorflow as tf

# Creating a constant
const_tensor = tf.constant([[1, 2], [3, 4]])
print("Constant Tensor:\n", const_tensor.numpy())

# Trying to change a constant (will raise an error)
# const_tensor[0, 0] = 10  # This line would raise an error


Constant Tensor:
 [[1 2]
 [3 4]]


TensorFlow Variable:

Characteristics:

Mutable: The values can be changed during execution.
Use Case: Primarily used to store parameters of the model that are updated during training (e.g., weights and biases).

In [9]:
# Creating a variable
var_tensor = tf.Variable([[1, 2], [3, 4]], dtype=tf.float32)
print("Variable Tensor Before Update:\n", var_tensor.numpy())

# Updating the variable
var_tensor.assign([[5, 6], [7, 8]])
print("Variable Tensor After Update:\n", var_tensor.numpy())


Variable Tensor Before Update:
 [[1. 2.]
 [3. 4.]]
Variable Tensor After Update:
 [[5. 6.]
 [7. 8.]]


3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
Matrix Addition:

Definition: Matrix addition involves adding two matrices of the same dimensions by adding corresponding elements.

In [10]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
D = tf.add(A, B)  # Or simply use A + B
print("Matrix Addition Result:\n", D.numpy())


Matrix Addition Result:
 [[ 6  8]
 [10 12]]


Matrix Multiplication:

Definition: Matrix multiplication (dot product) requires the number of columns in the first matrix to match the number of rows in the second matrix.

In [11]:
C = tf.constant([[1, 2], [3, 4]])
E = tf.matmul(A, C)  # Matrix multiplication
print("Matrix Multiplication Result:\n", E.numpy())


Matrix Multiplication Result:
 [[ 7 10]
 [15 22]]


Element-wise Operations:

Definition: Operations such as addition, subtraction, and multiplication can be performed directly on tensors of the same shape. In element-wise multiplication, corresponding elements are multiplied.

In [12]:
F = tf.constant([[2, 2], [2, 2]])
H = tf.multiply(A, F)  # Element-wise multiplication
print("Element-wise Multiplication Result:\n", H.numpy())


Element-wise Multiplication Result:
 [[2 4]
 [6 8]]


Part 2: Practical Implementation
Task 1: Creating and Manipulating Matrices

In [14]:
import tensorflow as tf

# 1. Create a normal matrix A with dimensions 3x3
A = tf.random.normal((3, 3))
print("Matrix A:\n", A.numpy())

# 2. Create a Gaussian matrix B with dimensions 4x4
B = tf.random.truncated_normal((4, 4))
print("Matrix B:\n", B.numpy())

# 3. Create a matrix C with dimensions 2x2 where values are drawn from a normal distribution
C = tf.random.normal((2, 2), mean=3.0, stddev=0.5)
print("Matrix C:\n", C.numpy())

# 4. Perform matrix addition between matrix A and a compatible submatrix of B
D = A + B[:3, :3]  # Only compatible shapes can be added
print("Matrix D (A + B):\n", D.numpy())

# 5. Create a new compatible matrix F with dimensions 2x3
F = tf.random.normal((2, 3))
print("Matrix F:\n", F.numpy())

# Now perform the multiplication between C (2x2) and F (2x3)
E = tf.matmul(C, F)  # This is now valid (2x2) @ (2x3)
print("Matrix E (C @ F):\n", E.numpy())


Matrix A:
 [[ 0.21114029  0.21881802 -0.20847815]
 [ 0.31332582 -0.5776927  -0.82318676]
 [-1.15434    -0.21699668  1.5093737 ]]
Matrix B:
 [[-0.20376937  1.5181134  -0.25146103  0.28863448]
 [-0.502681   -0.25703594  0.48537806 -0.7177125 ]
 [ 0.9476379   0.0194639   0.03880293  1.6027733 ]
 [-0.12785363 -0.29659668 -0.87301445  0.88008547]]
Matrix C:
 [[2.995787  2.3181176]
 [2.4577699 2.632454 ]]
Matrix D (A + B):
 [[ 0.00737092  1.7369314  -0.45993918]
 [-0.1893552  -0.8347286  -0.3378087 ]
 [-0.20670211 -0.19753279  1.5481766 ]]
Matrix F:
 [[ 0.27784184  0.6557665   0.18899478]
 [ 0.50615466  0.5742994  -0.69602805]]
Matrix E (C @ F):
 [[ 2.005681   3.2958302 -1.0472867]
 [ 2.0153     3.12354   -1.3677561]]


Task 2: Performing Additional Matrix Operations

In [15]:
# 1. Create a matrix F with dimensions 3x3 using random_uniform
F = tf.random.uniform((3, 3))
print("Matrix F:\n", F.numpy())

# 2. Calculate the transpose of matrix F
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G.numpy())

# 3. Calculate the element-wise exponential of matrix F
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F):\n", H.numpy())

# 4. Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (F concatenated with G):\n", I.numpy())

# 5. Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (F concatenated with H):\n", J.numpy())


Matrix F:
 [[0.8739524  0.8409716  0.12334979]
 [0.31426072 0.7745793  0.46403491]
 [0.61674285 0.9411752  0.74712706]]
Matrix G (Transpose of F):
 [[0.8739524  0.31426072 0.61674285]
 [0.8409716  0.7745793  0.9411752 ]
 [0.12334979 0.46403491 0.74712706]]
Matrix H (Element-wise Exponential of F):
 [[2.3963635 2.3186185 1.1312801]
 [1.3692467 2.1696792 1.5904785]
 [1.8528831 2.5629916 2.1109266]]
Matrix I (F concatenated with G):
 [[0.8739524  0.8409716  0.12334979 0.8739524  0.31426072 0.61674285]
 [0.31426072 0.7745793  0.46403491 0.8409716  0.7745793  0.9411752 ]
 [0.61674285 0.9411752  0.74712706 0.12334979 0.46403491 0.74712706]]
Matrix J (F concatenated with H):
 [[0.8739524  0.8409716  0.12334979]
 [0.31426072 0.7745793  0.46403491]
 [0.61674285 0.9411752  0.74712706]
 [2.3963635  2.3186185  1.1312801 ]
 [1.3692467  2.1696792  1.5904785 ]
 [1.8528831  2.5629916  2.1109266 ]]
